AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFormation template for RDS Aurora PostgreSQL with Subnet Groups and Encryption'

Parameters:
  DBName:
    Description: 'Name of the database'
    Type: String
  DBIdenfitierName:
    Description: 'Name of the database identifier' 
    Type: String
  DBSubnetGroupName:
    Description: 'Name of the database subnet group'
    Type: String
  SGName:
    Description: 'Name of the database'
    Type: String
  Environment:
    Description: 'Name of the environment'
    Type: String
  Application:
    Description: 'Name of the application'
    Type: String
  Engine:
    Description: 'Name of the engine'
    Type: String
  Increment:
    Description: 'Name of the increment'
    Type: Number
    Default: 1
    MinValue: 1
  AZ1:
    Description: 'Name of the database'
    Type: String
  AZ2:
    Description: 'Name of the database'
    Type: String
  MasterUsername:
    Description: 'Master username for the database'
    Type: String
  MinCapacity:
    Description: 'Master username for the database'
    Type: String
  MaxCapacity:
    Description: 'Master username for the database'
    Type: String
  MasterPassword:
    Description: 'Master password for the database'
    Type: String
    NoEcho: true
  EnableEncryption:
    Description: 'Enable storage encryption for the RDS cluster'
    Type: String
    Default: 'true'
    AllowedValues:
      - 'true'
      - 'false'

  Version:
    Description: 'PostgreSQL version'
    Type: String
    Default: '11.19'
    AllowedValues:
      - '11.18'
      - '11.19'
      - '11.20'
      - '11.21'
  VPCID:
    Description: 'VPC ID where the RDS will be hosted'
    Type: 'AWS::EC2::VPC::Id'
  SubnetIds:
    Description: 'Comma-separated list of existing subnet IDs where the RDS should be placed'
    Type: List<AWS::EC2::Subnet::Id>
  EnvironmentName:
    Type: String
    Default: "prod"
  EnvironmentName1:
    Type: String
  EnvironmentName2:
    Type: String
  PreferredBackupWindow:
    Description: 'Preferred backup window for the RDS cluster'
    Type: String
  PreferredMaintenanceWindow:
    Description: 'Preferred maintenance window for the RDS cluster'
    Type: String

Resources:
  SecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: 'Security group for RDS'
      GroupName: !Sub "RDS${Application}${SGName}${Environment}${Increment}" 
      Tags: 
        - Key: environment
          Value: !Ref EnvironmentName
        - Key: environment1
          Value: !Ref EnvironmentName1
        - Key: environment2
          Value: !Ref EnvironmentName2
        - Key: environment3
          Value:  staging
        - Key: environment4
          Value:  staging
        - Key: environment5
          Value:  staging
        - Key: environment6
          Value:  staging
        - Key: environment7
          Value:  staging
        - Key: environment8
          Value:  staging
      VpcId: !Ref VPCID
      SecurityGroupIngress:
        - IpProtocol: 'tcp'
          FromPort: '5432'
          ToPort: '5432'
          CidrIp: '0.0.0.0/0' # You should restrict this to only the necessary IPs


  DBSubnetGroup:
    Type: 'AWS::RDS::DBSubnetGroup'
    Properties:
      DBSubnetGroupName: !Sub "RDS${Application}${DBSubnetGroupName}${Environment}${Increment}" 
      DBSubnetGroupDescription: 'Subnet group for the RDS'
      SubnetIds: !Ref SubnetIds
      Tags: 
        - Key: environment
          Value: !Ref EnvironmentName
        - Key: environment1
          Value: !Ref EnvironmentName1
        - Key: environment2
          Value: !Ref EnvironmentName2
        - Key: environment3
          Value:  staging
        - Key: environment4
          Value:  staging
        - Key: environment5
          Value:  staging
        - Key: environment6
          Value:  staging
        - Key: environment7
          Value:  staging
        - Key: environment8
          Value:  staging

  RDSCluster:
    Type: 'AWS::RDS::DBCluster'
    Properties:
      Engine: 'aurora-postgresql'
      EngineMode: 'serverless'
      DBClusterIdentifier: !Sub "RDS${Application}${Engine}${Environment}${Increment}"
      EngineVersion: !Ref Version
      DatabaseName: !Ref DBName
      MasterUsername: !Ref MasterUsername
      MasterUserPassword: !Ref MasterPassword
      DBSubnetGroupName: !Ref DBSubnetGroup
      VpcSecurityGroupIds:
        - !Ref SecurityGroup
      StorageEncrypted: !Ref EnableEncryption
      BackupRetentionPeriod: 7
      DeletionProtection: false
      AvailabilityZones:
        - !Ref AZ1
        - !Ref AZ2
      ScalingConfiguration:
        AutoPause: false
        MinCapacity: !Ref MinCapacity
        MaxCapacity: !Ref MaxCapacity
      PreferredBackupWindow: !Ref PreferredBackupWindow
      PreferredMaintenanceWindow: !Ref PreferredMaintenanceWindow
      Tags: 
        - Key: environment
          Value: !Ref EnvironmentName
        - Key: environment1
          Value: !Ref EnvironmentName1
        - Key: environment2
          Value: !Ref EnvironmentName2
        - Key: environment3
          Value:  staging
        - Key: environment4
          Value:  staging
        - Key: environment5
          Value:  staging
        - Key: environment6
          Value:  staging
        - Key: environment7
          Value:  staging
        - Key: environment8
          Value:  staging
