AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFormation template for RDS Aurora PostgreSQL with Subnet Groups and Encryption'

Parameters:
  DBName:
    Description: 'Name of the database'
    Type: String
  DBIdenfitierName:
    Description: 'Name of the database'
    Type: String
  DBSubnetGroupName:
    Description: 'Name of the database'
    Type: String
  SGName:
    Description: 'Name of the database'
    Type: String
  AZ1:
    Description: 'Name of the database'
    Type: String
  AZ2:
    Description: 'Name of the database'
    Type: String
  MasterUsername:
    Description: 'Master username for the database'
    Type: String
  MasterPassword:
    Description: 'Master password for the database'
    Type: String
    NoEcho: true
  DBInstanceClass:
    Description: 'Instance class for the RDS'
    Type: String
  Version:
    Description: 'PostgreSQL version'
    Type: String
    Default: '11.9'
    AllowedValues:
      - '11.9'
      - '11.8'
      - '11.7'
      - '11.6'
  VPCID:
    Description: 'VPC ID where the RDS will be hosted'
    Type: 'AWS::EC2::VPC::Id'
  SubnetIds:
    Description: 'Comma-separated list of existing subnet IDs where the RDS should be placed'
    Type: List<AWS::EC2::Subnet::Id>
  EnvironmentName:
    Type: String
    Default: "prod"
  EnvironmentName1:
    Type: String
  EnvironmentName2:
    Type: String

Resources:
  SecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: 'Security group for RDS'
      GroupName: !Ref SGName
      Tags: 
        - Key: environment
          Value: !Ref EnvironmentName
        - Key: environment1
          Value: !Ref EnvironmentName1
        - Key: environment2
          Value: !Ref EnvironmentName2
        - Key: environment3
          Value:  staging
        - Key: environment4
          Value:  staging
        - Key: environment5
          Value:  staging
        - Key: environment6
          Value:  staging
        - Key: environment7
          Value:  staging
        - Key: environment8
          Value:  staging
      VpcId: !Ref VPCID
      SecurityGroupIngress:
        - IpProtocol: 'tcp'
          FromPort: '5432'
          ToPort: '5432'
          CidrIp: '0.0.0.0/0' # You should restrict this to only the necessary IPs


  DBSubnetGroup:
    Type: 'AWS::RDS::DBSubnetGroup'
    Properties:
      DBSubnetGroupName: !Ref DBSubnetGroupName
      DBSubnetGroupDescription: 'Subnet group for the RDS'
      SubnetIds: !Ref SubnetIds
      Tags: 
        - Key: environment
          Value: !Ref EnvironmentName
        - Key: environment1
          Value: !Ref EnvironmentName1
        - Key: environment2
          Value: !Ref EnvironmentName2
        - Key: environment3
          Value:  staging
        - Key: environment4
          Value:  staging
        - Key: environment5
          Value:  staging
        - Key: environment6
          Value:  staging
        - Key: environment7
          Value:  staging
        - Key: environment8
          Value:  staging

  RDSCluster:
    Type: 'AWS::RDS::DBCluster'
    Properties:
      Engine: 'aurora-postgresql'
      EngineMode: 'serverless'
      DBClusterIdentifier: !Ref DBIdenfitierName
      EngineVersion: !Ref Version
      DatabaseName: !Ref DBName
      MasterUsername: !Ref MasterUsername
      MasterUserPassword: !Ref MasterPassword
      DBSubnetGroupName: !Ref DBSubnetGroup
      VpcSecurityGroupIds:
        - !Ref SecurityGroup
      StorageEncrypted: true
      BackupRetentionPeriod: 7 # Number of days to retain backups
      DeletionProtection: false
      AvailabilityZones:
        - !Ref AZ1
        - !Ref AZ2
      ScalingConfiguration:
        AutoPause: true
        MinCapacity: 2
        MaxCapacity: 8
      Tags: 
        - Key: environment
          Value: !Ref EnvironmentName
        - Key: environment1
          Value: !Ref EnvironmentName1
        - Key: environment2
          Value: !Ref EnvironmentName2
        - Key: environment3
          Value:  staging
        - Key: environment4
          Value:  staging
        - Key: environment5
          Value:  staging
        - Key: environment6
          Value:  staging
        - Key: environment7
          Value:  staging
        - Key: environment8
          Value:  staging
