AWSTemplateFormatVersion: '2010-09-09'
Description: 'Nested Stack for SQS and Dead Letter Queue'
Parameters:
  QueueName:
    Description: 'Name of the main queue'
    Type: String

  DLQName:
    Description: 'Name of the dead letter queue'
    Type: String

  DelaySeconds:
    Description: 'The time, in seconds, for which the delivery of all messages in the queue is delayed'
    Type: Number

  MaxMessageSize:
    Description: 'The limit of how many bytes a message can contain before Amazon SQS rejects it'
    Type: Number

  MessageRetentionPeriod:
    Description: 'The length of time, in seconds, for which Amazon SQS retains a message'
    Type: Number

  VisibilityTimeout:
    Description: 'The length of time, in seconds, for which Amazon SQS prevents other consumers from receiving and processing the message'
    Type: Number

Resources:
  DeadLetterQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Ref DLQName

  MainQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Ref QueueName
      DelaySeconds: !Ref DelaySeconds
      MessageRetentionPeriod: !Ref MessageRetentionPeriod
      VisibilityTimeout: !Ref VisibilityTimeout
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt DeadLetterQueue.Arn
        maxReceiveCount: 5
