AWSTemplateFormatVersion: '2010-09-09'
Description: 'Nested Stack for SQS and Dead Letter Queue'
Parameters:
  QueueName:
    Description: 'Name of the main queue'
    Type: String

  DLQName:
    Description: 'Name of the dead letter queue'
    Type: String

  DelaySeconds:
    Description: 'The time, in seconds, for which the delivery of all messages in the queue is delayed'
    Type: Number

  MaxMessageSize:
    Description: 'The limit of how many bytes a message can contain before Amazon SQS rejects it'
    Type: Number

  MessageRetentionPeriod:
    Description: 'The length of time, in seconds, for which Amazon SQS retains a message'
    Type: Number

  VisibilityTimeout:
    Description: 'The length of time, in seconds, for which Amazon SQS prevents other consumers from receiving and processing the message'
    Type: Number

  Environment:
    Description: 'Name of the environment'
    Type: String
  Increment:
    Description: 'Name of the increment'
    Type: Number
    Default: 1
    MinValue: 1

  EnvironmentName:
    Type: String
    Default: "prod"
  EnvironmentName1:
    Type: String
  EnvironmentName2:
    Type: String


Resources:
  DeadLetterQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub "SQS${DLQName}${Environment}${Increment}"  
      Tags:
        - Key: environment
          Value: !Ref EnvironmentName
        - Key: environment1
          Value: !Ref EnvironmentName1
        - Key: environment2
          Value: !Ref EnvironmentName2
        - Key: environment3
          Value:  staging
        - Key: environment4
          Value:  staging
        - Key: environment5
          Value:  staging
        - Key: environment6
          Value:  staging
        - Key: environment7
          Value:  staging
        - Key: environment8
          Value:  staging

  MainQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub "SQS${QueueName}${Environment}${Increment}"  
      DelaySeconds: !Ref DelaySeconds
      MessageRetentionPeriod: !Ref MessageRetentionPeriod
      VisibilityTimeout: !Ref VisibilityTimeout
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt DeadLetterQueue.Arn
        maxReceiveCount: 5
      Tags:
        - Key: environment
          Value: !Ref EnvironmentName
        - Key: environment1
          Value: !Ref EnvironmentName1
        - Key: environment2
          Value: !Ref EnvironmentName2
        - Key: environment3
          Value:  staging
        - Key: environment4
          Value:  staging
        - Key: environment5
          Value:  staging
        - Key: environment6
          Value:  staging
        - Key: environment7
          Value:  staging
        - Key: environment8
          Value:  staging


